### ### ### ### ### ### ### ### ### ### 
### Options for analysis components ###
### ### ### ### ### ### ### ### ### ### 

output:
  likedir    : ./likelihood
  searchdir  : ./search
  mcmcdir    : ./mcmc
  simdir     : ./sims
  resultdir  : ./results
  plotdir    : ./plots
  likefile   : "likelihood_%08i_%s.fits"
  mergefile  :  merged_likelihood.fits
  roifile    :  merged_roi.fits
  labelfile  :  merged_labels.fits
  objectfile :  ugali_objects.fits
  assocfile  :  ugali_assocs.fits
  candfile   :  ugali_candidates.fits
  mcmcfile   : "%s_mcmc.npy"
  simfile    : "sims_%04i.fits"
  
batch:
  cluster: slac
  #cluster: local
  jobname: ugali
  opts : {}
  max_jobs: 250
  chunk: 100
  
scan:
  script : ugali/analysis/scan.py
  distance_modulus_array: [16.0, 16.5, 17.0, 17.5, 18.0, 18.5, 19.0, 19.5, 20.0, 20.5, 21.0, 21.5, 22.0, 22.5, 23.0, 23.5, 24.0]
  #distance_modulus_array: [18.0, 18.5, 19.0]
  #distance_modulus_array: [16.0 ]
  full_pdf: False
  color_lut_infile: null
  isochrone: null
  kernel:
    name: RadialPlummer
    r_h: 0.10
    r_t: 0.50
    proj: null
  
search:
  obj_threshold  : 10 # TS threshold for object selection
  cand_threshold : 25 # TS threshold for object selection
  xsize    : 1.0e+4
  minpix   : 1
  catalogs: [ [McConnachie12],                                        # ASSOC1
              [Rykoff14, Harris96, Corwen04, Nilson73]                # ASSOC2
            ]
  proximity: 0.1 # deg
  
mcmc:
  script : ugali/analysis/mcmc.py
  #params  : ['richness','lon','lat','extension','distance_modulus']
  #params  : ['richness','extension','ellipticity','position_angle']
  #params  : ['richness','lon','lat','extension','ellipticity','position_angle']
  params  : ['richness','lon','lat','extension']
  nwalkers: 100
  nsamples: 500
  nthreads: 16
  nburn   : 200
  isochrone: null
  kernel  :
      name: EllipticalPlummer
      r_h: 0.10
      r_t: 0.50
      e:   0.0
      theta: 0.0
      proj: 'ait'

simulate:
  script : ugali/simulation/simulator.py
  njobs  : 200
  size   : 10000
  save   : 3
  isochrone : null # default to using 'isochrone'
  kernel    : null # default to use 'kernel'
  params: 
    lon              : 45
    lat              : 45
    stellar_mass     : [0.0,0.0,'log']
    distance_modulus : [16.,24.,'linear']
    extension        : [0.1,0.1,'linear']
    ellipticity      : [0.0,0.0,'linear']
    
### ### ### ### ### ### ### ### ### ### 
### Options for building objects    ### 
### ### ### ### ### ### ### ### ### ### 
  
catalog:
  #infile: None
  dirname: /u/ki/kadrlica/sdss/data/dr10/healpix/
  basename: "catalog_hpx%04i.fits"
  lon_field: GLON
  lat_field: GLAT
  coordsys : gal
  # Color always defined as mag_1 - mag_2
  objid_field       : OBJID
  mag_1_field       : MAG_PSF_SFD_G 
  mag_err_1_field   : MAGERR_PSF_G
  mag_2_field       : MAG_PSF_SFD_R
  mag_err_2_field   : MAGERR_PSF_R
  mc_source_id_field: MC_SOURCE_ID
  #mc_source_id_field: None
  # True = band 1 is detection band; False = band 2 is detection band     
  band_1_detection: True 

# Deprecated?
mangle: 
  infile_1: /u/ki/kadrlica/sdss/data/dr10/mangle/sdss.dr10.holy.uni.ply
  infile_2: /u/ki/kadrlica/sdss/data/dr10/mangle/sdss.dr10.holy.uni.ply
  coordsys: gal
  #manglebindir: /home/s1/bechtol/des10.a/code/mangle/mangle2.2/bin}

mask:
  dirname    : /u/ki/kadrlica/sdss/data/dr10/simple
  basename_1 : "maglim_g_hpx%04i.fits"
  basename_2 : "maglim_r_hpx%04i.fits"
  minimum_solid_angle: 0.1 # deg^2
  # DEPRICATED
  infile_1: /u/gl/bechtol/disk/DES/mw_substructure/sv_test/y1c2/data/mask/hpx_4096_y1c2_coadd_holymolys_maglims_g_sparse_scaled.fits
  infile_2: /u/gl/bechtol/disk/DES/mw_substructure/sv_test/y1c2/data/mask/hpx_4096_y1c2_coadd_holymolys_maglims_r_sparse_scaled.fits
          
color:
  min   : -0.5
  max   : 1.0 # 1.0
  n_bins: 12  # 15

mag:
  min   : 18.5 # 18
  max   : 23   # 25
  n_bins: 70   # 0.1, 0.02

# HEALPix nside choices
# 2^4  -> 219. arcmin,  13.43 deg^2, 
# 2^5  -> 109. arcmin,   3.36 deg^2,
# 2^6  -> 55.0 arcmin,   0.84 deg^2, 3021 arcmin^2
# 2^7  -> 27.5 arcmin,   0.21 deg^2,  755 arcmin^2
# 2^8  -> 13.7 arcmin,  0.052 deg^2,  189 arcmin^2
# 2^9  -> 6.87 arcmin,  0.013 deg^2, 47.2 arcmin^2
# 2^10 -> 3.44 arcmin, 3.3e-3 deg^2, 11.8 arcmin^2
# 2^11 -> 1.72 arcmin, 8.2e-4 deg^2, 2.95 arcmin^2
# 2^12 -> 0.86 arcmin, 2.0e-4 deg^2, 0.74 arcmin^2
# 2^13 -> 0.43 arcmin, 5.1e-5 deg^2, 0.18 arcmin^2

coords:
  nside_catalog   : 4      # Size of patches for catalog binning
  nside_mask      : 64     # Size of patches for mask creation
  nside_likelihood: 256     # Size of target pixel
  nside_pixel     : 4096   # Size of pixels within target region
  roi_radius      : 2.0    # Outer radius of background annulus
  roi_radius_annulus: 0.5  # Inner radius of background annulus
  roi_radius_interior: 0.5 # Radius of interior region for likelihood analysis
  coordsys: gal
  proj_type: ait

data: 
  script : /u/ki/kadrlica/software/ugali/master/ugali/preprocess/database.py
  survey : sdss
  release: dr10
  dirname: /u/ki/kadrlica/sdss/data/dr10/raw
  density: "/u/ki/kadrlica/sdss/data/dr10/density/density_hpx%04i.fits"

# Default kernel specification
kernel:
  type: RadialPlummer
  params:
    r_h: 0.10
    r_t: 0.50
    proj: null
  
# Default isochrone specification
isochrone:
  mass_init_field: M_ini
  mass_act_field: M_act
  luminosity_field: logL/Lo
  mag_1_field: g
  mag_2_field: r
  stage_field: stage
  imf: Chabrier2003
  horizontal_branch_stage     : 'BHeb'
  #horizontal_branch_dispersion: null
  #horizontal_branch_dispersion: [0.0] # mag
  #horizontal_branch_dispersion: [-0.2, -0.1, 0.0, 0.1] # mag
  horizontal_branch_dispersion: 0.1
  #infiles: [/home/s1/bechtol/des10.a/projects/mw_substructure/stellar_evolution/isochrones/des/isota1010z0.1.dat
  #          /home/s1/bechtol/des10.a/projects/mw_substructure/stellar_evolution/isochrones/des/isota1010z0.2.dat
  #          /home/s1/bechtol/des10.a/projects/mw_substructure/stellar_evolution/isochrones/des/isota1015z0.1.dat
  #          /home/s1/bechtol/des10.a/projects/mw_substructure/stellar_evolution/isochrones/des/isota1015z0.2.dat]
  #fe/h = [-2.27,-1.5]; z    = [0.10 , 0.6]
  #age  = [8, 14]     ; age* = [090., 114.00]
  infiles: [/u/ki/kadrlica/sdss/data/isochrones/isota90.00z0.120.dat,
            /u/ki/kadrlica/sdss/data/isochrones/isota90.00z0.600.dat,
            /u/ki/kadrlica/sdss/data/isochrones/isota110.00z0.120.dat,
            /u/ki/kadrlica/sdss/data/isochrones/isota110.00z0.600.dat]
  weights: [0.25, 0.25, 0.25, 0.25]
  mass_steps: 400

likelihood:
  delta_mag: 0.03 # 1.e-3 
  spatial_only: False
  color_only:   False
  
color_lut:
  infile: null
  delta_mag: 0.03
  mag_err_array: [0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04]  
  distance_modulus_array: [16.0, 16.5, 17.0, 17.5, 18.0, 18.5, 19.0, 19.5, 20.0, 20.5, 21.0, 21.5, 22.0, 22.5, 23.0, 23.5, 24.0]

